### ISSUE TITLE
Same web property ID is tracked twice

### ISSUE THREAD

**Issue by kieusonlam** [nuxt-community/analytics-module#14]
I got `Same web property ID is tracked twice` on root url.

![image](https://user-images.githubusercontent.com/13093313/39408078-1b07ef76-4bfb-11e8-9dcd-0e020a3fb370.png)

There is someone have the same problem?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/analytics-module/issues/c13">#c13</a>)</em></sub></div>

**Comment by manniL** [comment]
Do you issue manual tracking in any `created` or `beforeCreated` hook?

**Comment by kieusonlam** [comment]
No I did not do any manual tracking.

Everything I did is add this to `nuxt.config.js`
```
  modules: [
    '@nuxtjs/google-analytics'
  ],
  'google-analytics': {
    id: 'UA-38944667-7'
  },
```
I found that it send page view for `/` every route I go
![image](https://user-images.githubusercontent.com/13093313/39434772-be6ba888-4cc3-11e8-8be1-cc7045fbb30b.png)

The solution that work for me right now is adding this to the `nuxt.config.js`
```
  'google-analytics': {
    id: 'UA-38944667-7',
    autoTracking: {
      pageviewOnLoad: false
    }
  }
```

**Comment by MatteoGabriele** [comment]
@kieusonlam the default behavior of the plugin within the nuxt module is to automatically track your routes by default.

If you don't want this to happen at all, you can turn that off and do it manually.
here the link to the documentation https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md#disable-page-auto-tracking

**Comment by MatteoGabriele** [comment]
I disagree :) 
Sending the first hit of the currently loaded page it's normal and even suggested in the Google Analytics developer documentation.
There are too many different use cases, someone wants it on page load, someone doesn't.

**Comment by failpunk** [comment]
Setting `pageviewOnLoad: false` prevents a double page hit on a SSR load.  With this on by default GA is logging double pageviews on the first site hit...this will screw all your analytics.  This is very dangerous as you can't ever change this.

**Comment by MatteoGabriele** [comment]
@pi0 I'm sorry but if I create a new nuxtjs project, add the plugin, the domain ID and start refreshing or going around, I don't have this issue.

without a reproduction, I can't do that much

**Comment by failpunk** [comment]
I wound up just creating and using my own simple plugin because of the issue in #8.

**Comment by stephanvane** [comment]
Hi,

I created a repository where this issue is reproduced. The issue is happening in the most basic nuxt-app possible, so it seems like it affects *all* users.

The repository can be found here: https://github.com/stephanvane/reproduction-issue-14

Using the official [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en), you can see that on the initial page-load, the page is tracked twice, it tracks the correct page **and** the root path (even when you're on an other page http://localhost:3000/page1). 

When navigating between pages, it's working as intended (tracking only once per click).

![issue](https://user-images.githubusercontent.com/411353/41846239-5d767f88-7876-11e8-82eb-baf68e5eed62.jpg)

here are the steps used to create this repository.

1. Create a new nuxt project
```
$ vue init nuxt-community/starter-template foo

$ yarn add @nuxtjs/google-analytics 
```

2. Add the module to `nuxt.config.js`:

```javascript
  modules: [
    // Simple usage
    ['@nuxtjs/google-analytics', {
      id: 'UA-12301-2'
    }]
  ],
```

3. Add another page, so there can be navigation between them.

4. *(optional)* Add `mode: 'spa'` to see that the issue is also there when SSR is disabled
```javascript
  mode: 'spa'
```

**Comment by MatteoGabriele** [comment]
hi @stephanvane thanks a lot for the effort, I will have a look as soon as possible

**Comment by ricardogobbosouza** [comment]
@MatteoGabriele The problem is not here?
https://github.com/MatteoGabriele/vue-analytics/blob/master/src/lib/page.js#L30
```js
set('page', page)
query('send', 'pageview', ...args)
```
Set and send the same page, that is, tracked twice

**Comment by pi0** [comment]
@ricardogobbosouza `set` prepares the event not sending it.

**Comment by ricardogobbosouza** [comment]
@pi0 yeah, but `query('send', 'pageview', ...args)` page reset `ga('send', 'pageview', '/')`
According to the [documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/pages) should only be `ga('send', 'pageview')`

**Comment by ricardogobbosouza** [comment]
The only thing I saw is that it executes these two commands
```
Running command: ga("set", "page", "/")
Running command: ga("send", "pageview", "/")
```
But I think that's okay. For me it works in both spa and universal mode.

**Comment by ricardogobbosouza** [comment]
As it's been some time, I think this has been solved.
For me it can close.
