### ISSUE TITLE
Migrate from analytics.js to gtag.js

### ISSUE THREAD

**Issue by ndro** [nuxt-community/analytics-module#9]
Hi,

We know that google migrate implementation analytics from **analytics.js** to **gtag.js** (src: https://developers.google.com/analytics/devguides/collection/gtagjs/migration).

So is this module support to **gtag.js**?

Because this module is using **vue-analytics** and in this [issue](https://github.com/MatteoGabriele/vue-analytics/issues/67), MatteoGabriele said that **vue-analytics** didn't yet support gtag.js.

Or, is there any solution to implementing "new" google analytics with gtag.js?

thanks

**Comment by MatteoGabriele** [comment]
hi @ndro 
The gtag.js documentation is still quite unclear to me, I'm still studying it. 

I have created a new package called vue-gtag few month ago, because the Api is quite different and I can't really add it to vue-analytics, but does nothing so far: still in development.

Google Analytics is still valid, is not going to be removed any time soon.

**Comment by ndro** [comment]
ah, thank you for your explanation... 👍
